# HTTP Server
[server]
	Address     = ":8520"
	ServerRoot  = "public"
	ServerAgent = "oh-my-anime_gf"
	LogPath     = "/tmp/log/oh-my-anime_gf/server"
	SessionMaxAge    = "72h"

# Logger.
[logger]
    Path        = "/tmp/log/oh-my-anime_gf"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:@tcp(127.0.0.1:3306)/anime_gf"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true